provide API to easily hash test data when constructing ClusteredTestD…
cqse/teamscale-jacoco-agent pull request #159
Opened 2020-09-08 12:17 UTC by karottenreibe

…etails

Addresses issue https://jira.cqse.eu/browse/TS-24353

- [x] Changes are tested adequately
- [x] Agent's README.md updated in case of user-visible changes
- [x] CHANGELOG.md updated
- [x] Present new features in [N&N](https://wiki.cqse.eu/pages/viewpage.action?pageId=689566)
- [x] [TGA Tutorial](https://docs.teamscale.com/tutorial/setting-up-tga-java) updated
- [x] [TIA Tutorial](https://docs.teamscale.com/tutorial/tia-java/) updated

Please respect the vote of the [Teamscale bot](https://demo.teamscale.com) or flag irrelevant findings as tolerated or false positives. If you feel that the Teamscale config needs adjustment, please state so in a comment and discuss this with your reviewer.

2020-09-08 12:19 UTC, karottenreibe commented
I fixed the architecture problem on master, so after merging, it should be gone :-)

2020-09-08 12:22 UTC, DreierF requested changes
Awesome 👏 

There are just some compile errors now because of the new constructor overload

2020-09-11 12:06 UTC, DreierF commented on CHANGELOG.md
> +- [feature] _tia-client_: add API to hash test data when creating ClusteredTestDetails
This should appear under next release

2020-09-11 12:09 UTC, karottenreibe commented
sorry, I'm ready for a vacation :P

2020-09-11 12:09 UTC, merged