TS-34497 Add basic cucumber test descriptor implementation
cqse/teamscale-jacoco-agent pull request #302
Opened 2023-08-17 14:49 UTC by AnonymFx

Addresses issue [TS-34497](https://cqse.atlassian.net/browse/TS-34497)

- [ ] Changes are tested adequately
- [ ] Agent's README.md updated in case of user-visible changes
- [ ] CHANGELOG.md updated
- [ ] Present new features in [N&N](https://wiki.cqse.eu/pages/viewpage.action?pageId=689566)
- [ ] [TGA Tutorial](https://docs.teamscale.com/tutorial/setting-up-tga-java) updated
- [ ] [TIA Tutorial](https://docs.teamscale.com/tutorial/tia-java/) updated

Please respect the vote of the [Teamscale bot](https://demo.teamscale.com) or flag irrelevant findings as tolerated or false positives. If you feel that the Teamscale config needs adjustment, please state so in a comment and discuss this with your reviewer.

2023-09-05 06:18 UTC, DreierF requested changes

2023-09-05 06:18 UTC, DreierF commented on impacted-test-engine/src/main/java/com/teamscale/test_impacted/test_descriptor/JUnitPlatformSuiteDescriptorResolver.java
> +		return Optional.of(suite + "/" + secondaryClusterId.get());
You could extract a method that determines the delegate `ITestDescriptorResolver` and accepts a lambda `(ITestDescriptorResolver) -> Optional<String>`, which will determine the suffix that should be appended to the suite. You should be able to reuse this for both methods and can hence get rid of the clone.

2023-09-06 09:44 UTC, AnonymFx commented on CHANGELOG.md
> +- [feature] Support for cucumber tests
Just mentioned the maven plugin because of https://cqse.atlassian.net/browse/TS-35531

2023-09-06 13:03 UTC, DreierF requested changes

2023-09-06 13:03 UTC, DreierF commented on impacted-test-engine/src/main/java/com/teamscale/test_impacted/test_descriptor/JUnitPlatformSuiteDescriptorResolver.java
> +							.toString() + "as " + nameOfValueToExtractForLogs + " as fallback.");
There is a space missing in `" as "`

2023-09-06 13:03 UTC, DreierF commented on impacted-test-engine/src/main/java/com/teamscale/test_impacted/test_descriptor/JUnitPlatformSuiteDescriptorResolver.java
> +					.toString() + "as " + nameOfValueToExtractForLogs + " as fallback.");
Same here

2023-09-06 14:06 UTC, merged